namespace Imp.Review;

// Walks the review window's diff and returns the filtered set of touched .cs
// files (plans/review-mode.md, FileEnumerator.cs slot).
//
// Filter (v1):
//   - include only *.cs
//   - drop deleted files (no current content to review)
//   - drop obj/, bin/, *.g.cs, *.Designer.cs, files with <auto-generated in
//     the first 5 lines
//   - drop tests (*Tests.cs or under Tests/) — no-op until tests exist
//   - non-.cs paths (Prompts, plans, csproj, json) skip per-file axes entirely
//
// Returns each file with line counts: current size (for the simplify-axis
// threshold) and diff size (added + deleted, for the simplify-axis threshold
// and for orchestrator prioritization).

public sealed record TouchedFile(
    string RelativePath,
    int CurrentLineCount,
    int DiffLineCount,
    bool IsProductionCode);

public static class FileEnumerator
{
    static readonly string[] ProductionRoots =
    {
        "Build/", "Research/", "Wiki/", "Tools/", "Safety/",
        "Infrastructure/", "Review/", "Substrate/",
    };

    public static List<TouchedFile> Enumerate(string repoRoot, ReviewWindow window)
    {
        var (paths, numstat) = LogTouched(repoRoot, window);

        var result = new List<TouchedFile>();
        foreach (var rel in paths)
        {
            if (!ShouldInclude(repoRoot, rel)) continue;

            var abs = Path.Combine(repoRoot, rel);
            if (!File.Exists(abs)) continue; // deleted

            // Defensive: skip files flagged as auto-generated by header marker.
            if (HasAutoGeneratedHeader(abs)) continue;

            var currentLines = CountLines(abs);
            var diffLines = numstat.TryGetValue(rel, out var n) ? n.Added + n.Deleted : 0;

            result.Add(new TouchedFile(
                RelativePath: rel,
                CurrentLineCount: currentLines,
                DiffLineCount: diffLines,
                IsProductionCode: IsProductionPath(rel)));
        }
        return result;
    }

    static (List<string> Paths, Dictionary<string, (int Added, int Deleted)> Numstat) LogTouched(
        string repoRoot, ReviewWindow window)
    {
        // git log --numstat collapses adds/dels per file across the window;
        // we sum them via the post-processed dictionary.
        var args = new List<string> { "log", "--numstat", "--pretty=format:" };
        if (window.FromSha is not null)
            args.Add($"{window.FromSha}..{window.HeadSha}");
        else if (window.DurationHint is not null)
            args.Add($"--since={window.DurationHint}");

        var r = GitCommand.Run(repoRoot, args.ToArray());
        var paths = new List<string>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var stats = new Dictionary<string, (int Added, int Deleted)>(StringComparer.Ordinal);

        if (!r.Ok) return (paths, stats);

        foreach (var rawLine in r.Stdout.Split('\n'))
        {
            var line = rawLine.Trim();
            if (line.Length == 0) continue;
            // Format: "<added>\t<deleted>\t<path>"; binary files show "-\t-\t<path>".
            var parts = line.Split('\t');
            if (parts.Length < 3) continue;
            var path = parts[2].Trim();
            if (path.Length == 0) continue;

            int added = int.TryParse(parts[0], out var a) ? a : 0;
            int deleted = int.TryParse(parts[1], out var d) ? d : 0;

            if (stats.TryGetValue(path, out var prev))
                stats[path] = (prev.Added + added, prev.Deleted + deleted);
            else
                stats[path] = (added, deleted);

            if (seen.Add(path)) paths.Add(path);
        }
        return (paths, stats);
    }

    static bool ShouldInclude(string repoRoot, string relPath)
    {
        if (!relPath.EndsWith(".cs", StringComparison.Ordinal)) return false;

        // Path-based exclusions
        var norm = relPath.Replace('\\', '/');
        if (norm.StartsWith("obj/") || norm.Contains("/obj/")) return false;
        if (norm.StartsWith("bin/") || norm.Contains("/bin/")) return false;
        if (norm.EndsWith(".g.cs", StringComparison.Ordinal)) return false;
        if (norm.EndsWith(".Designer.cs", StringComparison.Ordinal)) return false;

        // Tests — wired but no-op until tests exist.
        if (norm.EndsWith("Tests.cs", StringComparison.Ordinal)) return false;
        if (norm.Contains("/Tests/") || norm.StartsWith("Tests/")) return false;

        return true;
    }

    static bool HasAutoGeneratedHeader(string absPath)
    {
        try
        {
            using var sr = new StreamReader(absPath);
            for (int i = 0; i < 5 && !sr.EndOfStream; i++)
            {
                var line = sr.ReadLine();
                if (line is not null && line.Contains("<auto-generated", StringComparison.Ordinal))
                    return true;
            }
        }
        catch { /* unreadable → don't exclude on header grounds */ }
        return false;
    }

    static int CountLines(string absPath)
    {
        try
        {
            int n = 0;
            using var sr = new StreamReader(absPath);
            while (sr.ReadLine() is not null) n++;
            return n;
        }
        catch { return 0; }
    }

    static bool IsProductionPath(string relPath)
    {
        var norm = relPath.Replace('\\', '/');
        // Root-level .cs (e.g. Program.cs) counts.
        if (!norm.Contains('/')) return true;
        return ProductionRoots.Any(p => norm.StartsWith(p, StringComparison.Ordinal));
    }
}
